


#include <GDAL/gdal.h>




/* The parameter OFFSET specifies a small amount to be added the density in
 * every grid square, as a Fraction of the mean density on the whole
 * lattice.  This prevents negative densities from being generated by
 * numerical errors in the FFTs which can cause problems for the
 * integrator.  If the program is giving weird behavior, particularly at
 * the beginning of a calculation, try increasing this quantity by a factor
 * of 10.
 */

#define OFFSET 0.005



int equalize_density(char *infile, char *outfile, int fast, int accurate);




/* Function to read the density data from the GDAL file into the array rho.
 * Returns 1 if there was a problem, 0 otherwise
 */
int readpop(GDALRasterBandH hBand, double **rho, int xsize, int ysize);


// Function to make the grid of points
void creategrid(double *gridx, double *gridy, int xsize, int ysize);


// Writes the morphing grid out into a text file.
void writepoints(FILE *fp, double *gridx, double *gridy, int xsize, int ysize, 
				 double *adfGeoTransform);




double** cart_dmalloc(int xsize, int ysize);
void cart_dfree(double **userrho);
void cart_makews(int xsize, int ysize);
void cart_freews(int xsize, int ysize);
void cart_transform(double **userrho, int xsize, int ysize);
void cart_makecart(double *pointx, double *pointy, int npoints, int xsize, int ysize, double blur);



